name: Unit Tests Coverage

on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                node-version: ${{matrix.node-version}}
            - name: npm install
              run: npm ci
            - name: test
              run: npm test
            - name: code coverage
              run: npm test -- --coverage
            - name: Archive code coverage results
              uses: actions/upload-artifact@v3
              with:
                name: code-coverage-report
                path: /index.html